[build]
  command = "npm run build:netlify"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[scheduled.functions]]
  name = "cron-process"
  cron = "*/15 * * * *"
